# nginx/common.conf
# Файл подключается во все три конфигурации nginx
# Содержит логику безопасной обработки заголовка X-Forwarded-For

# Доверяем всей внутренней подсети, КРОМЕ шлюза хоста
geo $is_trusted_proxy {
    172.20.0.0/16   1; # Диапазон Docker-сети
    172.20.0.1      0; # Шлюз считается внешним клиентом, чтобы блокировать спуфинг с хоста
    default         0;
}

map $is_trusted_proxy $trusted_xff {
    1   $http_x_forwarded_for;  # Если свой, то цепочка дополняется
    0   $remote_addr;           # Если чужой, заголовог игнорируется, берётся реальный IP
}